// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Build 590 10/25/2017)
// Created on Mon Feb  5 14:06:57 2018

VGAController VGAController_inst
(
	.read_en(read_en_sig) ,	// output  read_en_sig
	.Blank(Blank_sig) ,	// output  Blank_sig
	.Hsync(Hsync_sig) ,	// output  Hsync_sig
	.Vsync(Vsync_sig) ,	// output  Vsync_sig
	.R(R_sig) ,	// output [7:0] R_sig
	.G(G_sig) ,	// output [7:0] G_sig
	.B(B_sig) ,	// output [7:0] B_sig
	.Clock25(Clock25_sig) ,	// input  Clock25_sig
	.Reset(Reset_sig) ,	// input  Reset_sig
	.Data(Data_sig) 	// input [23:0] Data_sig
);

